name: base
channels:
  - conda-forge
  - https://software.repos.intel.com/python/conda
  - ccpi
  - defaults
dependencies:
  # Notebook dependencies
  - ipywidgets
  - ipympl
  - widgetsnbextension
  - nodejs
  - numpy
  - cil # make synergistic notebooks work
  - astra-toolbox # needed for ct examples
  - scipy>=1.16
  - matplotlib
  - numba
  - llvmlite  # numba dependency
  - h5py
  - nibabel
  - scikit-image # nibabel dependency
  - PyWavelets # nibabel dependency
  - imageio # nibabel dependency
  - tqdm
  - docopt
  - pip
  - pip:
     - brainweb>=1.5.1
  # Developer dependencies
  - nbstripout
